version: '1'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes: 
      - ./client:/usr/src/client
      - node_modules:/usr/src/client/node_modules
      

  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/server
      - node_modules_b:/usr/src/server/node_modules
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes: 
  node_modules:
  node_modules_b:
  data:
    


  


    

    